---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/products":
    get:
      summary: Fetch all Products
      tags:
      - All products
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                properties:
                  name:
                    type: string
                  image:
                    type: string
                  price:
                    type: decimal
                  description:
                    type: text
                required:
                - name
                - image
                - price
                - description
            application/xml:
              schema:
                type: array
                properties:
                  name:
                    type: string
                  image:
                    type: string
                  price:
                    type: decimal
                  description:
                    type: text
                required:
                - name
                - image
                - price
                - description
    post:
      summary: Creates a product
      tags:
      - Create a product
      parameters: []
      responses:
        '201':
          description: Product created
        '503':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                image:
                  type: string
                price:
                  type: decimal
                description:
                  type: text
              required:
              - name
              - image
              - price
              - description
  "/api/v1/products/{id}":
    get:
      summary: show a product
      tags:
      - Show a product
      parameters:
      - name: id
        in: path
        schema:
          type: object
          properties:
            name:
              type: string
            image:
              type: string
            price:
              type: decimal
            description:
              type: description
          required:
          - id
          - name
          - image
          - price
          - description
        required: true
      responses:
        '200':
          description: Product found
    delete:
      summary: Delete a product
      tags:
      - Delete a product
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '204':
          description: Product deleted successfully
  "/api/v1/reservations":
    get:
      summary: Fetch all Reservations
      tags:
      - All reservations
      responses:
        '200':
          description: List of Reservations
          content:
            application/json:
              schema:
                type: array
                properties:
                  date:
                    type: date
                  city:
                    type: string
                  user_id:
                    type: integer
                  product_id:
                    type: integer
                required:
                - date
                - city
                - user_id
                - product_id
            application/xml:
              schema:
                type: array
                properties:
                  date:
                    type: date
                  city:
                    type: string
                  user_id:
                    type: integer
                  product_id:
                    type: integer
                required:
                - date
                - city
                - user_id
                - product_id
    post:
      summary: Creates a reservation
      tags:
      - Show a reservation
      parameters: []
      responses:
        '201':
          description: Product created
        '503':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: date
                city:
                  type: city
                user_id:
                  type: integer
                product_id:
                  type: integer
              required:
              - date
              - city
              - user_id
              - product_id
  "/api/v1/reservations/{id}":
    delete:
      summary: Delete a reservation
      tags:
      - Delete a reservation
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Reservation deleted successfully
  "/api/v1/signup":
    post:
      summary: Sign up User
      tags:
      - Sign Up
      parameters: []
      responses:
        '201':
          description: Sign up success
        '503':
          description: Invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
